name: roamie
description: "Find your roaming buddy."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.0.0
  image_picker: ^1.1.2
  image: ^4.5.4
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    # Google Sign-in assets: https://developers.google.com/identity/branding-guidelines
    - lib/assets/sign-in/
    - lib/assets/default_profilepic_roamie.png
    - lib/assets/icon/roamie_launcher.png
  fonts:
  # Font source: https://fonts.google.com/specimen/Poppins
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700